//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supertext.Sdl.Trados.FileType.JsonFile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonFileTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonFileTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supertext.Sdl.Trados.FileType.JsonFile.Resources.JsonFileTypeResources", typeof(JsonFileTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON.
        /// </summary>
        internal static string Invalid_Json_Format {
            get {
                return ResourceManager.GetString("Invalid_Json_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json could not be validated.
        /// </summary>
        internal static string Json_Could_Not_Be_Validated {
            get {
                return ResourceManager.GetString("Json_Could_Not_Be_Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file.
        /// </summary>
        internal static string Json_File {
            get {
                return ResourceManager.GetString("Json_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Supertext file type handles JSON (JavaScript Object Notation) files..
        /// </summary>
        internal static string Json_File_Filter_Description {
            get {
                return ResourceManager.GetString("Json_File_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files.
        /// </summary>
        internal static string Json_Files {
            get {
                return ResourceManager.GetString("Json_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon JsonFileIcon {
            get {
                object obj = ResourceManager.GetObject("JsonFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value path.
        /// </summary>
        internal static string Value_Path {
            get {
                return ResourceManager.GetString("Value_Path", resourceCulture);
            }
        }
    }
}
