//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supertext.Sdl.Trados.FileType.YamlFile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YamlFileTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YamlFileTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supertext.Sdl.Trados.FileType.YamlFile.Resources.YamlFileTypeResources", typeof(YamlFileTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid YAML.
        /// </summary>
        internal static string Invalid_Yaml_Format {
            get {
                return ResourceManager.GetString("Invalid_Yaml_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Value_Path {
            get {
                return ResourceManager.GetString("Value_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML could not be validated.
        /// </summary>
        internal static string Yaml_Could_Not_Be_Validated {
            get {
                return ResourceManager.GetString("Yaml_Could_Not_Be_Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML file.
        /// </summary>
        internal static string Yaml_File {
            get {
                return ResourceManager.GetString("Yaml_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Supertext file type handles YAML files..
        /// </summary>
        internal static string Yaml_File_Filter_Description {
            get {
                return ResourceManager.GetString("Yaml_File_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML files.
        /// </summary>
        internal static string Yaml_Files {
            get {
                return ResourceManager.GetString("Yaml_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon YamlFileIcon {
            get {
                object obj = ResourceManager.GetObject("YamlFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
