//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supertext.Sdl.Trados.FileType.PoFile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PoFileTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PoFileTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supertext.Sdl.Trados.FileType.PoFile.Resources.PoFileTypeResources", typeof(PoFileTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry location.
        /// </summary>
        internal static string Entry_Location {
            get {
                return ResourceManager.GetString("Entry_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry located at {0}-{1}.
        /// </summary>
        internal static string Entry_With_Location {
            get {
                return ResourceManager.GetString("Entry_With_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message context.
        /// </summary>
        internal static string Message_Context {
            get {
                return ResourceManager.GetString("Message_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO file.
        /// </summary>
        internal static string Po_File {
            get {
                return ResourceManager.GetString("Po_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Supertext file type handles GNU gettext PO files. It provides a setting to define which message is used as source and if the target should be displayed or not..
        /// </summary>
        internal static string Po_File_Filter_Description {
            get {
                return ResourceManager.GetString("Po_File_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO files.
        /// </summary>
        internal static string Po_Files {
            get {
                return ResourceManager.GetString("Po_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PoFileIcon {
            get {
                object obj = ResourceManager.GetObject("PoFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected line ({0}), next expected line patterns: {1}.
        /// </summary>
        internal static string Sniffer_Unexpected_Line {
            get {
                return ResourceManager.GetString("Sniffer_Unexpected_Line", resourceCulture);
            }
        }
    }
}
